- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/main.rs
- backend/src/routes/index.rs
> feat: Discover routes using `utoipa-actix-web`

- .github/workflows/ci.yaml
> feat: Created github workflows

- README.md
> feat: Added Repobeats to README.md

- .env.example
- backend/src/main.rs
> enhancement: Enabled changing backend ip by env

- .editorconfig
- frontend/app/assets/css/main.css
- frontend/app/pages/index.vue
- frontend/eslint.config.mjs
- frontend/eslint.config.ts
- frontend/nuxt.config.ts
- frontend/package.json
- pnpm-lock.yaml
> feat: Setup `@antfu/eslint-config` for improved formatting

- backend/README.md
> enhancement: Created backend readme

- backend/README.md
- backend/src/main.rs
> enhancement: Enabled Rust log level configuration with RUST_LOG env

- backend/src/main.rs
> feat: middleware logger

- .github/ISSUE_TEMPLATE/1-feature.yml
- .github/ISSUE_TEMPLATE/2-bug.yml
- .github/ISSUE_TEMPLATE/3-enhancement.yml
- .github/ISSUE_TEMPLATE/4-refactor.yml
> feat: Switch to issue types

- .github/workflows/ci.yaml
> fix: Run CI on external-repo PRs

- .github/workflows/ci.yaml
> fix: workflows run twice

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/main.rs
- backend/src/utils/app_state.rs
- backend/src/utils/env.rs
- backend/src/utils/jwt.rs
- backend/src/utils/mod.rs
- backend/src/utils/openapi.rs
- backend/tests/auth.rs
- backend/tests/teams.rs
> feat: Typed Env

- backend/src/routes/auth/oauth.rs
> fix: Fixed email being null in github oauth

- backend/package.json
- backend/rustfmt.toml
- backend/src/main.rs
- backend/src/middlewares/auth_middleware.rs
- backend/src/models/teams.rs
- backend/src/models/user.rs
- backend/src/routes/auth/login.rs
- backend/src/routes/auth/mod.rs
- backend/src/routes/auth/oauth/github.rs
- backend/src/routes/auth/oauth/google.rs
- backend/src/routes/auth/refresh.rs
- backend/src/routes/auth/register.rs
- backend/src/routes/index.rs
- backend/src/routes/teams/create_team.rs
- backend/src/routes/teams/mod.rs
- backend/src/routes/teams/my_team.rs
- backend/src/routes/teams/view_team.rs
- backend/src/routes/teams/view_teams.rs
- backend/src/routes/user.rs
- backend/src/utils/env.rs
- backend/src/utils/error.rs
- backend/src/utils/jwt.rs
> Refactor: Error split

- frontend/app/app.vue
> fix(frontend): Correct nuxt page min-h

- frontend/nuxt.config.ts
> enhancement(frontend): Force dark mode

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/main.rs
> [Feat]: Rate limiting for auth services

- frontend/app/components/Auth.vue
> feat: Form validation

- frontend/nuxt.config.ts
Resolves: #45 
website description written by Michał Markiewicz
> feat: Improved website description (#45)

- .gitmodules
- .husky/post-checkout
- .husky/pre-commit
- backend/Cargo.lock
- backend/Cargo.toml
- backend/README.md
- backend/src/main.rs
- backend/src/routes/mod.rs
- backend/src/routes/task/background.rs
- backend/src/routes/task/icon.rs
- backend/src/routes/task/list.rs
- backend/src/routes/task/mod.rs
- backend/src/routes/task/story.rs
- backend/src/utils/app_state.rs
- backend/src/utils/env.rs
- backend/src/utils/error.rs
- backend/src/utils/mod.rs
- backend/src/utils/task.rs
> feat: Tasks endpoints

- frontend/app/app.vue
- frontend/nuxt.config.ts
> [Enhancement]: og tag color

- backend/src/models/teams.rs
- backend/src/routes/teams/mod.rs
> feat: Added limit of 5 users per team

- backend/src/lib.rs
> Enhancement: Enabled permissive cors for /tasks endpoints

- backend/Cargo.lock
- backend/Cargo.toml
- backend/openapi-check/src/main.rs
- backend/src/lib.rs
- backend/src/main.rs
- backend/src/models/user.rs
- backend/tests/auth.rs
- backend/tests/utils.rs
Depends on #187 
Resolves #32 
More tests, proper mocking etc. will be implemented in separate PR
> feat(backend): Implement db integration tests using sqlite

- backend/src/services/emails.rs
- backend/src/utils/error.rs
> fix(backend): Include email assets in binary

- .github/dependabot.yml
- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/routes/auth/register.rs
- backend/src/routes/teams/create.rs
- backend/src/routes/teams/management/rename.rs
> enhancement: Added request validator

- backend/src/models/team_invites.rs
- backend/src/routes/teams/mod.rs
> fix: Disallowed multiple invitations for one user

- backend/src/lib.rs
- backend/src/middlewares/auth.rs
- backend/src/middlewares/event.rs
- backend/src/middlewares/mod.rs
- backend/src/models/user.rs
- backend/src/utils/error.rs
> feat: Event middleware

- frontend/app/error.vue
> Enhancement: Display more information on error page

- frontend/app/components/Map.vue
- frontend/app/pages/tasks/index.vue
> feat(frontend): Add different shadow for completed tasks

- backend/src/routes/flag/mod.rs
- backend/src/routes/flag/submit.rs
- backend/tests/flag.rs
> enhancement: Disalllowed unconfirmed teams from submiting flag

- frontend/app/components/TaskDescription.vue
> feat: Added task assets to description page

- frontend/app/components/TaskDescription.vue
- frontend/app/components/panel/tile/Main.vue
- frontend/app/pages/leaderboard.vue
- frontend/app/pages/panel/index.vue
It just makes our website usable once again by:
- fixing 500 error codes on server load
- properly displaying `WithoutTeam` tile
> fix: Random frontend bugfixes

- backend/src/routes/admin/email/mod.rs
- backend/src/routes/admin/mod.rs
- backend/src/routes/admin/tasks/mod.rs
- backend/src/routes/admin/teams/mod.rs
- backend/src/routes/admin/users/mod.rs
- backend/src/routes/auth/mod.rs
- backend/src/routes/event/mod.rs
- backend/src/routes/flag/mod.rs
- backend/src/routes/leaderboard/mod.rs
- backend/src/routes/task/assets/mod.rs
- backend/src/routes/task/mod.rs
- backend/src/routes/teams/invitations/mod.rs
- backend/src/routes/teams/management/mod.rs
- backend/src/routes/teams/mod.rs
> refactor(frontend): Replace `cfg` abbreviation with `config`

- frontend/nuxt.config.ts
- frontend/package.json
- pnpm-lock.yaml
Resolves #367
I removed nuxt/scripts due to it being unused and causing build issues
> fix(frontend): Correct website title

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/routes/teams/management/mod.rs
- backend/src/services/env.rs
- backend/tests/auth.rs
> fix(backend): Use proper default env config for tests

- frontend/app/components/panel/tile/Main.vue
- frontend/app/components/panel/tile/WithTeam.vue
- frontend/app/middleware/auth.global.ts
- frontend/app/middleware/guest.ts
- frontend/app/middleware/tasks.global.ts
- frontend/app/pages/leaderboard.vue
- frontend/app/pages/panel/index.vue
- frontend/app/pages/panel/team.vue
- frontend/app/pages/tasks/index.vue
- frontend/app/pages/tasks/solution/[id].vue
- frontend/app/pages/tasks/story/[id].vue
- frontend/nuxt.config.ts
- frontend/package.json
- pnpm-lock.yaml
Resolves #95
It was very painful, but I did it.
> fix(frontend): Switch to `nuxt-open-fetch-x`

- backend/src/services/auth.rs
> enhancement: Use polish names for sending emails

- backend/src/middlewares/auth.rs
- backend/src/routes/flag/submit.rs
> feat: Created middleware for confirmed teams

- frontend/nuxt.config.ts
- frontend/package.json
- pnpm-lock.yaml
> feat(frontend): Add `compodium` dev module

- bun.lock
- frontend/app/components/Auth.vue
- frontend/app/components/panel/tile/WithTeam.vue
- frontend/package.json
Resolves #274
Grouping icon updates PRs will be added in #430
> feat: Include icons in `package.json`

- backend/Cargo.lock
- backend/Cargo.toml
- backend/locales/error.yaml
- backend/macros/Cargo.toml
- backend/macros/src/lib.rs
- backend/macros/src/macros/localized_error.rs
- backend/macros/src/macros/mod.rs
- backend/macros/src/macros/updatable_model.rs
- backend/src/routes/auth/mod.rs
- backend/src/routes/flag/mod.rs
- backend/src/routes/task/mod.rs
- backend/src/routes/teams/mod.rs
- backend/src/utils/error.rs
> feat(backend): Localize error messages

- frontend/app/components/AnimatedText.vue
- frontend/app/components/StoryViewer.vue
- frontend/tests/components/AnimatedText.test.ts
> fix(frontend): Fix story page

- backend/locales/error.yaml
- backend/src/lib.rs
- backend/src/utils/error.rs
- backend/tests/auth.rs
> fix(backend): Properly serialize validation errors

- .env.example
- .husky/pre-commit
- bun.lock
- frontend/app/pages/tasks/index.vue
- frontend/package.json
- frontend/tests/pages/tasks/index.spec.ts
- frontend/tests/setup.ts
- frontend/vitest.config.ts
> fix(frontend): Various fixes

- frontend/app/components/panel/tile/Main.vue
- frontend/app/utils/duration.ts
- frontend/tests/utils/duration.test.ts
> fix(frontend): Properly display complex durations

- backend/src/models/user.rs
- backend/src/routes/account/update.rs
- backend/src/routes/auth/register.rs
- backend/src/routes/teams/create.rs
- backend/src/routes/teams/management/rename.rs
- backend/tests/routes/auth.rs
> fix: nickname censorship

- .dockerignore
- frontend/Dockerfile
- frontend/app/components/Footer.server.vue
- frontend/app/components/LogoWithText.vue
- frontend/app/components/Navbar.vue
- frontend/app/components/primitive/SocialIcon.vue
- frontend/app/composables/useGitInfo.ts
- frontend/app/layouts/static-page.vue
- frontend/app/pages/docs/[slug].vue
- frontend/app/pages/faq.vue
- frontend/app/pages/index.vue
- frontend/app/utils/gitInfo.ts
- frontend/content/footer-socials.ts
- frontend/nuxt.config.ts
resolves #485 
depends on #504
> feat(frontend): Footer component

- .github/workflows/ci.yaml
> enhancement(frontend): Use frozen lockfile in `ci.yaml`

- bun.lock
- frontend/app/components/hero/HeroSection.vue
- frontend/app/components/hero/SocialMediaContainer.vue
- frontend/app/components/primitive/OrderedList.vue
- frontend/app/components/primitive/SocialIcon.vue
- frontend/app/components/section/HowToParticipate.vue
- frontend/app/pages/index.vue
- frontend/content/how-to-participate.json
- frontend/package.json
> feat(frontend): how-to-register component

- frontend/app/pages/index.vue
- frontend/tests/e2e/navbar-mobile.test.ts
> fix: adjust container height to remove unnecessary full-screen styling

- frontend/app/components/ElevatedButton.vue
- frontend/app/pages/index.vue
Approved by the best designer in our team :3
> feat(frontend): Use primary background color for `ElevatedButton`

- frontend/content/faq.json
@Norbiros you had some additional questions and concerns, if I remember correctly. Drop them down in the comments, and I will add them :3
> enhancement(frontend): update faq

- frontend/app/components/hero/DesktopHeroBackground.vue
- frontend/app/components/hero/HeroSection.vue
> fix: repeating images on niche resolutions

- frontend/app/components/AuthForm.vue
- frontend/app/layouts/centered.vue
- frontend/app/pages/account/submit_personal_info.vue
- frontend/app/pages/admin/register_external_team.vue
- frontend/app/pages/request_password_reset.vue
- frontend/app/pages/reset_password.vue
Resolves: @Norbiros death threats
> fix: Add responsivnes to centered layout and description to personal info form

- frontend/content/info-tiles.ts
> feat(frontend): update reward info

- frontend/app/components/Navbar.vue
> feat(frontend): Made text on button on Navbar dynamic

- frontend/app/app.vue
- frontend/app/assets/css/main.css
- frontend/app/components/AuthForm.vue
- frontend/app/components/hero/HeroSection.vue
- frontend/app/layouts/centered.vue
- frontend/app/layouts/default.vue
- frontend/tests/e2e/navbar-mobile.test.ts
> fix(frontend): Ensure all pages have proper min-h

- frontend/app/components/AuthForm.vue
- frontend/app/components/primitive/TransparentInput.vue
It was possible thanks to Norbiros.
> Enhancement: Show password button

- frontend/app/error.vue
> Enhancement: Handle custom 404 error messages

- frontend/app/app.vue
> fea(frontend): add `NuxtRouteAnnouncer` to improve a11y

- backend/src/main.rs
- backend/src/models/email_verification_request.rs
- backend/tests/mod.rs
- backend/tests/models/email_verification_model.rs
- backend/tests/models/mod.rs
> enhancement: Delete expired email verification requests on server startup

- frontend/app/assets/css/main.css
- frontend/app/components/Navbar.vue
- frontend/tests/e2e/error-modal.test.ts
> fix(frontend): Spacing Class overlap; UModal with no inner width

- .github/workflows/ci.yaml
- backend/rust-toolchain.toml
- renovate.json
> enhancement: Pin rust to specific version and enable rust updates in renovate
